name: "android-release"

on:
  push:
    tags:
      - "v*"

jobs:
  quick-build:
    runs-on: ubuntu-22.04

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: 缓存 pnpm 仓库
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装前端依赖
        run: pnpm install --no-frozen-lockfile

      - name: 安装 Rust stable 及 Android 目标
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: 缓存 Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
          cache-all-crates: true

      - name: 缓存系统依赖
        uses: actions/cache@v4
        id: system-cache
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: 安装系统依赖
        if: steps.system-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: 缓存 Gradle 包和分发文件
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
            src-tauri/gen/android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 缓存 Android SDK
        uses: actions/cache@v4
        id: android-cache
        with:
          path: |
            ${{ env.ANDROID_HOME }}
            ~/.android
          key: ${{ runner.os }}-android-sdk-34-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-34-
            ${{ runner.os }}-android-sdk-

      - name: 设置 Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 设置 Android SDK
        uses: android-actions/setup-android@v3

      - name: 安装 Android SDK 组件
        if: steps.android-cache.outputs.cache-hit != 'true'
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;26.1.10909125" \
            "cmdline-tools;latest"

      - name: 设置 Android 环境变量
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: 设置 Android 签名密钥（如有密钥）
        run: |
            if [ -n "${{ secrets.KEYSTORE }}" ]; then
              echo "${{ secrets.KEYSTORE }}" | base64 -d > doki-release-key.keystore
              echo "✅ 已还原 doki-release-key.keystore 文件"
            else
              echo "⚠️ 未找到签名密钥，将构建未签名APK"
            fi

      - name: 更新 tauri.conf.json 版本号
        run: |
          VERSION="${GITHUB_REF_NAME}"
          VERSION="${VERSION#v}"
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" src-tauri/tauri.conf.json
          echo "Updated version to: $VERSION"

      - name: 缓存前端构建
        uses: actions/cache@v4
        id: frontend-cache
        with:
          path: |
            dist
            .next
            node_modules/.cache
          key: ${{ runner.os }}-frontend-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml', 'src/**', 'public/**') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: 构建前端
        if: steps.frontend-cache.outputs.cache-hit != 'true'
        run: pnpm build

      - name: 缓存 Tauri Android 生成
        uses: actions/cache@v4
        id: tauri-android-cache
        with:
          path: src-tauri/gen/android
          key: ${{ runner.os }}-tauri-android-${{ hashFiles('src-tauri/tauri.conf.json', 'src-tauri/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-tauri-android-

      - name: 初始化 Tauri Android 项目（如有需要）
        if: steps.tauri-android-cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -d "src-tauri/gen/android" ]; then
            pnpm tauri android init
          fi

      - name: 设置 Gradle wrapper 并修复下载问题
        run: |
          cd src-tauri/gen/android

          # 检查gradle-wrapper.properties
          if [ -f gradle/wrapper/gradle-wrapper.properties ]; then
            echo "当前Gradle配置："
            cat gradle/wrapper/gradle-wrapper.properties
            
            sed -i 's|https://services.gradle.org/distributions/|https://downloads.gradle.org/distributions/|g' gradle/wrapper/gradle-wrapper.properties
            
            cat gradle/wrapper/gradle-wrapper.properties
          fi

          # 验证gradlew权限
          chmod +x gradlew

          # 尝试预下载Gradle（带重试机制）
          echo "预下载Gradle包..."
          for i in {1..3}; do
            echo "尝试 $i/3..."
            if ./gradlew --version; then
              echo "✅ Gradle下载成功"
              break
            else
              echo "⚠️ 第$i次尝试失败，等待10秒后重试..."
              sleep 10
            fi
            
            if [ $i -eq 3 ]; then
              echo "❌ Gradle下载失败，尝试手动下载..."
              
              # 手动下载Gradle
              GRADLE_VERSION=$(grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties | cut -d'/' -f6 | cut -d'-' -f2)
              echo "检测到Gradle版本: $GRADLE_VERSION"
              
              mkdir -p ~/.gradle/wrapper/dists/gradle-$GRADLE_VERSION-bin
              cd ~/.gradle/wrapper/dists/gradle-$GRADLE_VERSION-bin
              
              # 尝试多个下载源
              GRADLE_URLS=(
                "https://downloads.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"
                "https://github.com/gradle/gradle/releases/download/v$GRADLE_VERSION.0/gradle-$GRADLE_VERSION-bin.zip"
                "https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"
              )
              
              for url in "${GRADLE_URLS[@]}"; do
                echo "尝试从 $url 下载..."
                if wget -q --timeout=30 --tries=2 "$url"; then
                  echo "✅ 手动下载成功"
                  break
                fi
              done
            fi
          done


      - name: 安装所有 Android Rust 目标
        run: |
          echo "安装所有Android Rust目标..."
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi  
          rustup target add i686-linux-android
          rustup target add x86_64-linux-android
          echo "✅ 所有Android Rust目标已安装"

      - name: 构建所有平台的 Android APK
        run: |
          echo "开始构建Android APK"
          export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs=-Xmx2g"
          pnpm gen

      - name: 列出生成的 APK 文件
        run: |
          echo "检查生成的APK文件..."

          # 检查原始APK目录
          ORIGINAL_APK_DIR="src-tauri/gen/android/app/build/outputs/apk/universal/release"
          if [ -d "$ORIGINAL_APK_DIR" ]; then
            echo "原始APK目录内容："
            ls -la "$ORIGINAL_APK_DIR"
          fi

          echo ""
          echo "查找所有APK文件（包括重命名后的）："
          find . -name "*.apk" -type f -exec ls -lh {} \; | while read line; do
            echo "  $line"
          done

          APK_COUNT=$(find . -name "*.apk" -type f | wc -l)
          echo ""
          echo "总共找到 $APK_COUNT 个APK文件"

      - name: 创建 Android 发布并上传 APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "APP ${{ github.ref_name }}"
          draft: false
          prerelease: false
          body: ""
          files: |
            **/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
